import requests
from bs4 import BeautifulSoup
import csv

#Project to web-scrape the first 5 pages of Laptops in Amazon India website for the Laptop Names, Price and Ratings
#and insert it into a csv file. 
#Final copy

# use proxies in requests so as to proxy your request via a proxy server
# as some sites may block the IP if traffic generated by an IP is too high
proxies = {
  'http': 'http://134.119.205.253:8080',
  'https': 'http://134.119.205.253:8080',
}
all=[]
serial_no=0
page_no=6
headers={"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"}
with open ('Amazon_Laptops.csv','w',encoding="utf-8") as new_file:
    csv_writer=csv.writer(new_file,delimiter=',',lineterminator='\n') 
    for i in range(1,page_no):
        all.append('----------------------------'+'Page '+str(i)+'-------------------------------------------------')
        csv_writer.writerow(all) 
        r = requests.get("https://www.amazon.in/s?k=laptops&page="+str(i), headers=headers)#, proxies=proxies)
        content = r.content
        soup = BeautifulSoup(content)   


        for d in soup.findAll('div', attrs={'class':'sg-col-4-of-12 sg-col-8-of-16 sg-col-16-of-24 sg-col-12-of-20 sg-col-24-of-32 sg-col sg-col-28-of-36 sg-col-20-of-28'}):
            serial_no=serial_no+1
            name = d.find('span', attrs={'class':'a-size-medium a-color-base a-text-normal'})
            price = d.find('span', attrs={'class':'a-offscreen'})
            rating = d.find('span', attrs={'class':'a-icon-alt'})
            all=[]

            if serial_no is not None:
                all.append(serial_no)
            else:
                all.append('')

            if name is not None:
                all.append(name.text)
            else:
                all.append("unknown-product")

            if price is not None:
                all.append(price.text)
            else:
                all.append('$0')

            if rating is not None:
                all.append(rating.text)
            else:
                all.append('-1')
            csv_writer.writerow(all)  
            all=[]
